cabal-version:      2.4
name:               aptrace
version:            0.1.0.0
synopsis:           Bare-metal Cortex-M firmware analysis and symbolic execution, built on Macaw/Crucible/What4
build-type:         Simple

library
  exposed-modules:  APTrace.VectorTable
                  , APTrace.FirmwareLoader
                  , APTrace.SymbolicRunner
                  , APTrace.ProtocolHarness
                  , APTrace.DebugHarness
                  , APTrace.MacawCensus
  hs-source-dirs:   src
  default-language: Haskell2010
  ghc-options:      -Wall
  build-depends:    base
                  , aeson
                  , asl-translator
                  , bytestring
                  , binary
                  , bv-sized
                  , containers
                  , crucible
                  , crucible-debug
                  , crucible-llvm
                  , crucible-macaw-debug
                  , crucible-syntax
                  , macaw-base
                  , macaw-aarch32
                  , macaw-aarch32-symbolic
                  , macaw-symbolic
                  , microlens
                  , parameterized-utils
                  , semmc-aarch32
                  , text
                  , time
                  , vector
                  , what4

executable aptrace
  main-is:          Main.hs
  hs-source-dirs:   app
  default-language: Haskell2010
  ghc-options:      -Wall
  build-depends:    base
                  , bytestring
                  , containers
                  , microlens
                  , parameterized-utils
                  , prettyprinter
                  , aptrace
                  , macaw-base
                  , macaw-aarch32

test-suite aptrace-test
  type:             exitcode-stdio-1.0
  main-is:          Main.hs
  hs-source-dirs:   test
  default-language: Haskell2010
  ghc-options:      -Wall
  build-depends:    base
                  , aeson
                  , bytestring
                  , containers
                  , microlens
                  , parameterized-utils
                  , prettyprinter
                  , aptrace
                  , macaw-base
                  , macaw-aarch32
